server:
   port: 8888

spring:
   profiles: 
     active: prod
   cloud:
     config:
       server:
         bootstrap: true
         git:
           uri: https://github.com/dhms/eats
           search-paths: config
        
   sleuth:
     sampler:
       percentage: .10